from __future__ import annotations
from datetime import date,datetime
from typing import Any,Protocol
from uuid import UUID
from app.retrieval.models import EvidenceSet
from app.security.context import SecurityContext
from app.signing.evidence_package import SignedEvidencePackage
class DocumentRepository(Protocol):
    def retrieve(self,query:str,context:SecurityContext,jurisdiction:str,as_of:date,known_at:datetime,limit:int=8)->EvidenceSet:...
class GraphRepository(Protocol):
    def query_template(self,context:SecurityContext,jurisdiction:str,terms:set[str],limit:int=50)->list[dict[str,Any]]:...
class ProvenanceRepository(Protocol):
    def save_claim(self,*,claim_id:UUID,context:SecurityContext,text:str,status:str,classification:str,jurisdiction:str,lineage:dict[str,Any])->None:...
    def load_claim_transitively(self,claim_id:UUID)->dict[str,Any]:...
class AuditRepository(Protocol):
    def append(self,context:SecurityContext,event_type:str,resource:str,metadata:dict[str,Any])->dict[str,Any]:...
    def verify_tenant(self,context:SecurityContext)->dict[str,Any]:...
class SecurityDecisionRepository(Protocol):
    def save(self,context:SecurityContext,resource_type:str,resource_id:str,operation:str,decision:str,reason:str)->None:...
class EvidencePackageRepository(Protocol):
    def save(self,package:SignedEvidencePackage)->None:...
    def get(self,package_id:UUID)->SignedEvidencePackage:...
